### PR TITLE
Added MIT license, so that it would be possible to use this code.

### PR DESCRIPTION
**Pull request by xet7**
Added MIT license, so that it would be possible to use this code.

### CODE REVIEW

**Comment by secretGeek** [comment]
Hey @xet7 I appreciate that your heart is pure and I see that your work is solid and good -- but I fear for your very soul ---

Do you actually intend to *use* this code? Do you realise how dangerous that could be? And do you think it's a wise idea to do anything to allow others to use this code? Would you open a corner store and start selling cigarettes and handguns to toddlers at cheap prices?

I probably will approve this merge request but I just want to understand your motives a little here.... 

(And for selfish reasons, I may be able to submit your chain of reasoning as a case study to a noted psychiatric journal)

**Comment by xet7** [comment]
@secretGeek 

This is the only web framework that does not have license at my Frameworks wiki page:

https://github.com/howinfo/howinfo/wiki/Frameworks

Here is more stuff I have done:

https://github.com/wekan/wekan/wiki/Deep-Dive-Into-WeKan

https://github.com/wekan/wekan/wiki/WeKan-Multiverse-Roadmap

Coding with all web frameworks is my therapy. It's similar like this Unbox Therapy channel:

https://www.youtube.com/@unboxtherapy

There are also web browsers developed by others for therapy reasons https://github.com/wekan/wekan/wiki/WeKan-Multiverse-Roadmap#browsers-developed-for-therapy-reasons

**Comment by xet7** [comment]
@secretGeek 

 > (And for selfish reasons, I may be able to submit your chain of reasoning as a case study to a noted psychiatric journal)

Yes, you have my permission to use my chain of reasoning as a case study to a noted psychiatric journal. Please send copy of that case study article to my email support@wekan.team . Thanks!

**Comment by secretGeek** [comment]
Thank you for this contribution.

**Comment by xet7** [comment]
@secretGeek 

Thanks a lot ! I updated wiki page https://github.com/howinfo/howinfo/wiki/Frameworks to show that this has MIT license.

**Pull request merged**
